world_frame_id: "odom"
segment_point_cloud_topic: "/example/object_segmentation"
# segment_point_cloud_topic: "/example/raw_pcl"

use_label_propagation: true # check if we use label
semantic_instance_segmentation:
  enable_semantic_instance_segmentation: false
  class_tsdk: "coco80"

method: "fast"

voxblox:
  voxel_size: 0.01
  voxels_per_side: 16
  truncation_distance_factor: 5.0
  voxel_carving_enabled: false
  allow_clear: true
  min_ray_length_m: 0.1
  max_ray_length_m: 3

pairwise_confidence_merging:
  enable_pairwise_confidence_merging: true
  merging_min_overlap_ratio: 0.1
  merging_min_frame_count: 2


meshing:
  visualize: true
  update_mesh_every_n_sec: 1.0
  publish_scene_mesh: false

publishers:
  publish_scene_map: false
  publish_scene_mesh: true
  publish_object_bbox: false

icp:
  enable_icp: false
  keep_track_of_icp_correction: true

debug:
  verbose_log: true
  multiple_visualizers: false
  save_visualizer_frames: false